### ISSUE TITLE
About zend.

### ISSUE THREAD

**Issue by lpj145** [laminas/laminas-zendframework-bridge#17]
- [] I was not able to find an [open](https://github.com/laminas/laminas-zendframework-bridge/issues?q=is%3Aopen) or [closed](https://github.com/laminas/laminas-zendframework-bridge/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on our [forums](https://discourse.laminas.dev/).)

Sorry, but i don't can access forum... all zend packages now are called "laminas" ? my questions is about my long change framework to zend structure...

again, sorry for this issue.

**Comment by RobQuistNL** [comment]
No, not yet: https://github.com/zendframework/zendframework

Laminas will be the new name and this package 

> provides a custom autoloader that aliases legacy Zend Framework, Apigility, and Expressive classes to their replacements under the Laminas Project.

**Comment by lpj145** [comment]
ok, i love way's what zend solved the problems, and avaliable for help, thanks!

**Comment by weierophinney** [comment]
@lpj145 We have provided information on https://getlaminas.org about what will happen. At this stage, we are close to launching the technical project, and we encourage you to [help test the migration tooling](https://gist.github.com/weierophinney/df937d870b0d8bded4d1185ef510aaed).
