### ISSUE TITLE
Make autoloader a bit faster

### ISSUE THREAD

**Issue by vv12131415** [laminas/laminas-zendframework-bridge#19]
https://github.com/laminas/laminas-zendframework-bridge/blob/0d159d8d7580e78b8a20b317e6c669cf11a14e04/src/Autoloader.php#L22

You can make anonymous function as static one, and it will load a little bit faster.

**Comment by michalbundyra** [comment]
> You can make anonymous function as static one, and it will load a little bit faster.

Only PHP 5.4+. We support PHP 5.3 here.
See: https://github.com/laminas/laminas-zendframework-bridge/commit/2eeb7d9f0284b4d3fc71d1289c761340a738508d

**Comment by vv12131415** [comment]
@webimpress oh, sorry, didn't know that
