### ISSUE TITLE
Support for zend-stratigility v2

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-zendframework-bridge#2]
We need to add autoloader override for zend-stratigility v2 functions.

**Comment by weierophinney** [comment]
I was thinking these hadn't changed at all, and then I noticed that the typehints change due to the functions being developed pre-PSR-15 adoption.

I think I can manage this via conditional definitions; I'll create a PR shortly.

**Comment by weierophinney** [comment]
Closing. #7 will resolve this, but the agreed upon solution is to create proxy functions in each package that defines them during the filter-tree operation.
