### ISSUE TITLE
laminas.dev website is down

### ISSUE THREAD

**Issue by maestroevn** [laminas/laminas-zendframework-bridge#26]
https://docs.laminas.dev/laminas-zendframework-bridge/
https://discourse.laminas.dev/

**Comment by michalbundyra** [comment]
@tigranmaestro I would say it is no up yet ;-) 

We are testing migration and planning the full migration to Laminas in this month.
See: https://gist.github.com/weierophinney/df937d870b0d8bded4d1185ef510aaed

**Comment by weierophinney** [comment]
Yes - this is a known issue.

The migration tooling is rewriting URLs to their final locations, but those URLs will not be functional until we cut over to the new repositories.
