### ISSUE TITLE
Migration from ZendFramework on old PHP

### ISSUE THREAD

**Issue by DeyV** [laminas/laminas-zendframework-bridge#43]
Some projects that use ZendFramework still support old php versions. 
For example PHPOffice / PHPWord  >= php 5.3

#### Summary

laminas-zendframework-bridge require >= 5.6 and is required even in old tags just rewrited to laminas (great job btw), tags used by older php versions 

#### Previous behavior

Old php 5.3 - 5.5 projects use old tags of ZendFramework, whichout additional dependencies. 

#### Current behavior

After switch to Laminas, every tag in every laminas repo require this project, 

```
 - laminas/laminas-escaper 2.2.0 requires laminas/laminas-zendframework-bridge ^1.0 -> satisfiable by laminas/laminas-zendframework-bridge[1.0.0].

...

  - laminas/laminas-zendframework-bridge 1.0.0 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
  - Installation request for laminas/laminas-escaper ^2.2 -> satisfiable by laminas/laminas-escaper[2.2.0, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1].

```

https://travis-ci.org/PHPOffice/PHPWord/builds/632169932?utm_medium=notification&utm_source=github_status

#### How to fix

Change requirements in composer to php >=5.3

**Comment by thexpand** [comment]
If I'm not mistaken, these version are not supported by the PHP core team anymore, why adding support for them on our side, then?

**Comment by DeyV** [comment]
Of course - they are obsolete and nobody should. 

But if You want fast migration from zf to laminas - it should be really easy process. 
For example - why did your team take the time to rewrite the old ones tags and old obsolete versions? 

Without this fix  - most of this work is useless.

**Comment by thexpand** [comment]
Yes, that makes sense - projects that require older version of specific `zendframework/zend-*` packages should be able to easily migrate to the same version `laminas/laminas-*` packages, hence the support for older PHP versions for `laminas/laminas-zendframework-bridge`. Thanks for the clarification.

**Comment by DeyV** [comment]
My MR for this problem. https://github.com/laminas/laminas-zendframework-bridge/pull/44
