### ISSUE TITLE
The bridge does not seem to work in all cases

### ISSUE THREAD

**Issue by stof** [laminas/laminas-zendframework-bridge#64]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

#### Summary

We got many reports that `ocramius/proxy-manager` 2.2 (which was using `zendframeword/zend-code`) breaks when using the `laminas/laminas-code` replacement. See https://github.com/symfony/symfony/issues/35934 and https://github.com/doctrine/DoctrineMigrationsBundle/issues/300 for instance.
It looks like the bridge is not foolproof.

**Comment by michalbundyra** [comment]
@stof we believe it was a problem with composer and it is fixed now.
For reference please see:
https://github.com/laminas/laminas-code/issues/37
https://github.com/composer/composer/issues/8622

**Comment by weierophinney** [comment]
@stof Can you provide an update? Is this still an issue, or is it resolved when using a current Composer version?

**Comment by stof** [comment]
I was not the one having issues. I was the one triaging the Symfony and Doctrine issues.

**Comment by stof** [comment]
@mmarton @andchir as you were the one reporting the issues to Symfony and Doctrine, can you tell us whether updating Composer to 1.10+ fixed the issue ?

**Comment by mmarton** [comment]
I no longer have it. But i have no idea what fixed it. New versions have been released since then  from composer, laminas and doctrinemigrations

**Comment by dennisameling** [comment]
Updating to Composer 1.10+ fixed the issue for us. Related [changelog entry](https://github.com/composer/composer/blob/master/CHANGELOG.md#1100-2020-03-10):

> Fixed issue where --no-dev autoload generation was excluding some packages which should not have been excluded
