### ISSUE TITLE
Bridge does not work with zend i18

### ISSUE THREAD

**Issue by rimvislt** [laminas/laminas-zendframework-bridge#77]
### Bug Report

TypeError : Argument 1 passed to Laminas\View\Helper\HeadTitle::setTranslator() must be an instance of Laminas\I18n\Translator\TranslatorInterface or null, instance of Zend\Mvc\I18n\Translator given

modules.config.php
...
'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'Zend\\I18n',
    'Zend\\Mvc\\I18n',
....

Composer versions:
"zendframework/zend-mvc": "~3.1",
"zendframework/zend-cache": "^2.7.1",
"zendframework/zend-mvc-i18n": "^1.1",

**Comment by weierophinney** [comment]
Have you performed a migration to Laminas yet? This package is supposed to be used within a Laminas application in order to allow 3rd party components that depend on ZF components to work. Adding it to a ZF application will not generally work.

Please follow the [migration documentation](https://docs.laminas.dev/migration/) and then report back if you have errors. If you do, please provide a full list of components installed (using `composer show`) so we can determine which components might have conflicts.

**Comment by ThanksOihyuo** [comment]
> ### Bug Report
> 
> 
> 
> TypeError : Argument 1 passed to Laminas\View\Helper\HeadTitle::setTranslator() must be an instance of Laminas\I18n\Translator\TranslatorInterface or null, instance of Zend\Mvc\I18n\Translator given
> 
> 
> 
> modules.config.php
> 
> ...
> 
> 'Zend\\Db',
> 
>     'Zend\\Filter',
> 
>     'Zend\\Hydrator',
> 
>     'Zend\\InputFilter',
> 
>     'Zend\\Paginator',
> 
>     'Zend\\Router',
> 
>     'Zend\\Validator',
> 
>     'ZF\\Apigility',
> 
>     'ZF\\ApiProblem',
> 
>     'ZF\\Configuration',
> 
>     'ZF\\OAuth2',
> 
>     'ZF\\MvcAuth',
> 
>     'ZF\\Hal',
> 
>     'ZF\\ContentNegotiation',
> 
>     'ZF\\ContentValidation',
> 
>     'ZF\\Rest',
> 
>     'ZF\\Rpc',
> 
>     'ZF\\Versioning',
> 
>     'Zend\\I18n',
> 
>     'Zend\\Mvc\\I18n',
> 
> ....
> 
> 
> 
> 
> 
> Composer versions:
> 
> "zendframework/zend-mvc": "~3.1",
> 
> "zendframework/zend-cache": "^2.7.1",
> 
> "zendframework/zend-mvc-i18n": "^1.1",
> 
> 
> 
> 
> 
>

**Comment by froschdesign** [comment]
@ThanksOihyuo 
Please follow the migration guide otherwise laminas-zendframework-bridge will not work.
