### ISSUE TITLE
Unaccaptable performance hit

### ISSUE THREAD

**Issue by beberlei** [laminas/laminas-zendframework-bridge#83]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | all

#### Summary

The bridge prepend autoloader runs on all autoloaded classes regardless of what package they are from. The implementation is not very efficient and adds unacceptable overhead of 4ms for a regular Symfony request of 200ms. The problem imho is that a lot of laminas components always include this bridge, even though the README of this component states differently:

> This package should be installed only if you are also using the composer plugin that installs Laminas packages to replace ZF/Apigility/Expressive packages.

#### Current behavior

Expensive logic detecing class aliasing is run on every class regardless if it starts with `Zend` or not.

#### How to reproduce

Run a Profiler on any script with for example laminas/laminas-event-manager 3.3.1 as a composer dependency, for example any Symfony that includes `friendsofphp/proxy-manager-lts`. Here from Tideways:

![laminas1](https://user-images.githubusercontent.com/26936/120182186-5b2df000-c20e-11eb-989a-f2e9b57304f8.png)

#### Expected behavior

At the very least let the autoloader early exit with `if (strpos($class, 'Zend') !== 0) { return; }`. 

But better would be not to enable this autoloader automatically via `"autoload": {"files":` key.

In addition this package should not be included in other laminas packages by default such as `laminas/laminas-eventmanager`: https://github.com/laminas/laminas-eventmanager/blob/3.4.x/composer.json#L27

**Comment by Ocramius** [comment]
I think this mostly needs documentation improvements:

 * the fact that this package is included by default in `laminas/*` packages is intentional, and can only be mitigated by **removal** of the requirement in the next major release: this is because anyone requiring `zendframework/*` packages (and packages in its ecosystem) will get compatible `laminas/*` packages, and we cannot just break those until a new major release of the `laminas/*` packages is here. This is not clear, and multiple people have asked about it.
 * the package can be safely shadowed via `"replace": {"laminas/laminas-zendframework-bridge": "*"}` if you are running within an environment where you no longer rely on `zendframework/*` packages. This needs to be better documented, or perhaps added to the output of `composer install`, as an additional plugin output that warns about the performance pitfalls. This has to remain an opt-in, until people stop having `zendframework/*` in their dependencies overall.
 * 2% overhead for something that is removed with a one-liner (where safe to do so) seems OK.

**Comment by beberlei** [comment]
@Ocramius I agree that 2% overhead is ok when it can be removed with a one liner, but as you mentioned this is not documented and i wasn't aware it was so easy to get around it. Thank you for mentioning it.

**Comment by Ocramius** [comment]
Question is how to make this more visible now: do you think that adding it to the output of `composer install` would suffice?

Seems like the cleanest approach to literally **force** people to know that this thing is actively doing something.

**Comment by beberlei** [comment]
@Ocramius Just realized for fast requests that are in the 10-20ms range the overhead becomes 10% though :-(

![laminas2](https://user-images.githubusercontent.com/26936/120184475-51f25280-c211-11eb-8d35-65dbcc102c40.png)

**Comment by Ocramius** [comment]
For that, I think a perf optimization is valid.

Perhaps we can add a `phpbench/phpbench` test to verify the impact long-term, and patch this stuff:

https://github.com/laminas/laminas-zendframework-bridge/blob/ff8e9a7832de38fc329eb7cc0bc2b9bdaeddb819/src/Autoloader.php#L124-L171

**Comment by beberlei** [comment]
We rolled this out to production now and monitoring on the autoloader shows the heavy effect, average autoloading time increases from 1 ms to 3ms on a 9ms average response time.

![Screenshot from 2021-05-31 17-39-38](https://user-images.githubusercontent.com/26936/120216584-7eb96080-c237-11eb-9f38-205dde1883f6.png)

**Comment by Ocramius** [comment]
Have you tried rolling out the `replace:` suggestion? That is pretty much
**the** way this is supposed to be handled, until the entire Zend ->
Laminas rename unfortunate fallout (sigh, american copyright laws) is over.

**Comment by beberlei** [comment]
I am running into trouble getting it to work in combination with https://github.com/beberlei/composer-monorepo-plugin/ but hope to find a solution soon.

**Comment by Ocramius** [comment]
@beberlei I've identified that `laminas/laminas-code` no longer needs `laminas/laminas-eventmanager` in its core, so I'm releasing a new minor today with the removed dependency (and therefore the performance hit should be gone, if you only need it for the proxying mechanisms)

**Comment by Ocramius** [comment]
@beberlei FYI, there's work in progress to completely phase out `laminas/laminas-zendframework-bridge`.

For now, we're probing this on some individual packages, like we did in https://github.com/laminas/laminas-stdlib/pull/33

If that proves to be successful, we will go on and implement this for all other packages.

**Comment by PowerKiKi** [comment]
Most Laminas and Mezzio packages have been updated (and released) to remove the dependency on this package.

The only one left, and on which I cannot do anything anymore, are:

- https://github.com/mezzio/mezzio-authentication-oauth2/pull/38
- https://github.com/laminas/laminas-xml2json/pull/9
- https://github.com/laminas/laminas-mvc-plugin-fileprg/pull/17
- https://github.com/laminas/laminas-barcode/pull/13

**Comment by Ocramius** [comment]
Two of the above left: we can then probably phase out this package completely, and call this dark chapter of ZendFramework "done" :|

**Comment by PowerKiKi** [comment]
I think this issue can be closed because the very last PR to stop using this package is about to be merged and released.

**Comment by Ocramius** [comment]
Which one is that? 🤔

**Comment by PowerKiKi** [comment]
https://github.com/laminas/laminas-mvc-plugin-fileprg/pull/17#issuecomment-1005989977

**Comment by Ocramius** [comment]
Awesome, released! 💪

I'd say that this package needs to be abandoned soon-ish then.

**Comment by hostep** [comment]
> I think this issue can be closed because the very last PR to stop using this package is about to be merged and released.

As far as I can see, the last released version of `laminas/laminas-server` [still includes this](https://github.com/laminas/laminas-server/blob/2.11.0/composer.json#L27). It got removed as dependency about 2 years ago [over here](https://github.com/laminas/laminas-server/commit/d47435d6bec7f9be85863dc45323320432e103bc#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34), but this didn't get released yet. Maybe that can happen as well soonish? Thanks! 🙂

**Comment by Ocramius** [comment]
@hostep send a patch

**Comment by Ocramius** [comment]
Closing here: this component is slowly being phased out anyway, so your focus should be to migrate.
