### ISSUE TITLE
ClassLoader type

### ISSUE THREAD

**Issue by Androlax2** [laminas/laminas-zendframework-bridge#88]
Hello,

Got a bug on another repository : https://github.com/Rareloop/lumberjack-core/issues/35

Is this from here or from this repo ?

**Comment by Ocramius** [comment]
Possibly related to a combination of incompatible dependencies.

Check:

 * your `composer.lock`, specifically which versions of this library you have installed
 * your `composer --version`

**Comment by Androlax2** [comment]
Hello @Ocramius 

Here are the versions locked in my composer.lock for each laminas package : 

```
"name": "laminas/laminas-diactoros",
"version": "2.8.0",
```

```
"name": "laminas/laminas-zendframework-bridge",
"version": "1.4.0",
```

And my composer version : 

Composer version 2.1.12

**Comment by Androlax2** [comment]
Okay, I found the incompatibility, It don't come from here, see:  https://github.com/wp-media/imagify-plugin/issues/639

**Comment by boesing** [comment]
Hm, with composer v2 and composer v3, the `vendor/autoload.php` always returns an instance of `Composer\Autoload\ClassLoader`.

Somehow, your error message states that this is not the case. Thats kinda weird but might be solved with #90 (even tho it is not supposed to solve it that way).

Maybe double-checking the plugin you are referring to might help to find the reason on why the autoloader file does not return an instance of `Composer\Autoload\ClassLoader`.

**Comment by Androlax2** [comment]
Yeah for some reason `vendor/autoload.php` return an instance of `Composer\Autoload\ClassLoader` but with some extra letters and numbers on the `Autoload` namespace

**Comment by Androlax2** [comment]
Okay, I found the plugin where came the problem : [https://github.com/dangoodman/composer-for-wordpress/blob/master/ComposerForWordpress.php](https://github.com/dangoodman/composer-for-wordpress/blob/master/ComposerForWordpress.php)

**Comment by Androlax2** [comment]
https://github.com/dangoodman/composer-for-wordpress/blob/master/ComposerForWordpress.php#L58

**Comment by boesing** [comment]
Okay, closing here as this is unrelated to this repository.

No one should mess around with composer internals imho.
Thanks for pointing this out, @Androlax2!

**Comment by Androlax2** [comment]
If this is really needed for the plugin, maybe Composer could implement an interface on `ClassLoader` so you could add that interface in the type ?
