### ISSUE TITLE
"ZendForm" getting replaced in 3rd party module

### ISSUE THREAD

**Issue by patrick-braun** [laminas/laminas-zendframework-bridge#93]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.5.0, current commit (581d11fe5691b0b84d1f7f89dd5812d6a58d979f) as of this report

#### Summary

We have an internal module called KrumediaZendFormBinder which is getting renamed to KrumediaLaminasFormBinder which leads to a NotFound exception.

#### Current behavior

The phrase "ZendForm" is getting replaced in 3rd party modules.

#### How to reproduce

This is a failing test case which could be added to ReplacementsTest.php

```PHP
yield 'MyZendForm' => [
    'MyZendFormBinder\Controller\Plugin\BinderPlugin',
    'MyZendFormBinder\Controller\Plugin\BinderPlugin',
];
```
#### Expected behavior

The ZendframeworkBridge does not touch 3rd party module names.

#### Potential fix

A potential fix could be adding

```PHP
    'aZendForm' => 'aZendForm',
    'bZendForm' => 'bZendForm',
    'cZendForm' => 'cZendForm',
    'dZendForm' => 'dZendForm',
    'eZendForm' => 'eZendForm',
    'fZendForm' => 'fZendForm',
    'gZendForm' => 'gZendForm',
    'hZendForm' => 'hZendForm',
    'iZendForm' => 'iZendForm',
    'jZendForm' => 'jZendForm',
    'kZendForm' => 'kZendForm',
    'lZendForm' => 'lZendForm',
    'mZendForm' => 'mZendForm',
    'nZendForm' => 'nZendForm',
    'oZendForm' => 'oZendForm',
    'pZendForm' => 'pZendForm',
    'qZendForm' => 'qZendForm',
    'rZendForm' => 'rZendForm',
    'sZendForm' => 'sZendForm',
    'tZendForm' => 'tZendForm',
    'uZendForm' => 'uZendForm',
    'vZendForm' => 'vZendForm',
    'wZendForm' => 'wZendForm',
    'xZendForm' => 'xZendForm',
    'yZendForm' => 'yZendForm',
    'zZendForm' => 'zZendForm',
```

to the `replacements.php` rules. A similar batch is already in there for `'aZend' => 'aZend'` etc.

Though I don't know if there is a case where SomethingZendForm actually needs to be replaced with SomethingLaminasForm.

I'd gladly send a PR with this fix (and test) if it results in the intended behavior.

**Comment by Ocramius** [comment]
Unclear to me what the problem is: a patch with a failing test case + potential fix would be very welcome, in order to better explain what is going on 👍

**Comment by patrick-braun** [comment]
I have created a minimal project structure that errors out, the `laminas-project` is just the `laminas-skeleton-application` with the minimal controller plugin in `custom-zend-form-binder`.
`composer install` in both folders and the crash happens on opening the `/application/test` route.

If I add the
`"CustomZendFormBinder" => "CustomZendFormBinder"`
line to 
`laminas-project\vendor\laminas\laminas-zendframework-bridge\config\replacements.php`
to block that replacement explicitely it does not crash anymore.

[example-project.zip](https://github.com/laminas/laminas-zendframework-bridge/files/8520120/example-project.zip)

**Comment by Ocramius** [comment]
What's the observed crash?

Note: no, I can't check your example project - needs to be part of the test suite here.
